### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Thedonsolo** [optiosteam/payconiq-client-php#2]
Hi, 
I get an error when using the callback verification:
[2021-02-23 12:34:02] DEV2.ERROR: Something went wrong while loading and verifying the JWS. Error: Unable to load and verify the token. {"exception":"[object] (Optios\\Payconiq\\Exception\\PayconiqCallbackSignatureVerificationException(code: 0): Something went wrong while loading and verifying the JWS. Error: Unable to load and verify the token. at /var/www/myapp/vendor/optiosteam/payconiq-client-php/src/PayconiqCallbackSignatureVerifier.php:127)

Code:
//$this->paymentprofileid = '5exxxxxxxxxxxx2';
//$signature = 'yJ0eXAiOiJKT1...............................................................................XQ';
//$payload = '{"paymentId":"5e2xxxxxxxxxxxxxba01f","transferAmount":6050,"tippingAmount":0,"amount":6050,"totalAmount":6050,"reference":"9378-01A0","createdAt":"2021-02-23T11:37:15.362Z","expireAt":"2021-02-23T11:40:15.362Z","succeededAt":"2021-02-23T11:37:33.498Z","status":"SUCCEEDED","debtor":{"name":"Test","iban":"*************24680"},"currency":"EUR"}';

$payconiqCallbackSignatureVerifier = new PayconiqCallbackSignatureVerifier($this->paymentprofileid, null, null, false);

$valid = $payconiqCallbackSignatureVerifier->isValid($signature, $payload);
//$valid = empty string...

$jwsvalid = $payconiqCallbackSignatureVerifier->loadAndVerifyJWS($signature, $payload);
--> ERROR (see above) IS THROWN

**Comment by simonwestyn** [comment]
Hi @Thedonsolo,

In the above code snippet you posted, I see that most variables are commented out. Could it be that you are passing non-existing parameters to the functions?

To debug what is going on, you might want to add a `var_dump` or similar to the `try { } catch()` in `vendor/web-token/jwt-signature/JWSLoader.php` around line 106.

E.g.:

```php
try {
            $jws = $this->serializerManager->unserialize($token);
            $nbSignatures = $jws->countSignatures();
            for ($i = 0; $i < $nbSignatures; ++$i) {
                if ($this->processSignature($jws, $keyset, $i, $payload)) {
                    $signature = $i;

                    return $jws;
                }
            }
        } catch (Throwable $e) {
            var_dump($e); //<<<<<<<<<<< to figure out what is going wrong
            // Nothing to do. Exception thrown just after
        }

        throw new Exception('Unable to load and verify the token.');
```

Please post back the error that you receive there.

**Comment by Thedonsolo** [comment]
Hi Simon, 

Thanks for your prompt reply!
The catch is never entered:


    public function loadAndVerifyWithKeySet(string $token, JWKSet $keyset, ?int &$signature, ?string $payload = null): JWS
    {
        try {
            Log::info('A1 '.$token);
            $jws = $this->serializerManager->unserialize($token);
            Log::info('A2 ',(array)$jws);

            $nbSignatures = $jws->countSignatures();
            Log::info('A1 '.$jws->countSignatures());
            for ($i = 0; $i < $nbSignatures; ++$i) {
                Log::info('A2 ',(array)$jws);
                if ($this->processSignature($jws, $keyset, $i, $payload)) {
                    $signature = $i;

                    return $jws;
                }
            }
        } catch (Throwable $e) {
            Log::info('ERROR:',(array)$e);
            // Nothing to do. Exception thrown just after
        }

        throw new Exception('Unable to load and verify the token.');
    }



A1 : eyJ0.............................cg
A2: {"\u0000Jose\\Component\\Signature\\JWS\u0000isPayloadDetached":true,"\u0000Jose\\Component\\Signature\\JWS\u0000encodedPayload":null,"\u0000Jose\\Component\\Signature\\JWS\u0000signatures":[{"Jose\\Component\\Signature\\Signature":[]}],"\u0000Jose\\Component\\Signature\\JWS\u0000payload":null} 

Stacktrace:

ERROR: Something went wrong while loading and verifying the JWS. Error: Unable to load and verify the token. {"exception":"[object] (Optios\\Payconiq\\Exception\\PayconiqCallbackSignatureVerificationException(code: 0): Something went wrong while loading and verifying the JWS. Error: Unable to load and verify the token. at /var/www/myapp/vendor/optiosteam/payconiq-client-php/src/PayconiqCallbackSignatureVerifier.php:127)
[stacktrace]
#0 /var/www/myapp/app/Http/Controllers/PayconiqController.php(137): Optios\\Payconiq\\PayconiqCallbackSignatureVerifier->loadAndVerifyJWS('eyJ0eXAiOiJKT1N...', '{\"paymentId\":\"d...')
#1 /var/www/myapp/routes/web.php(179): App\\Http\\Controllers\\PayconiqController->verifyCallback(Array, 'eyJ0eXAiOiJKT1N...')
#2 /var/www/myapp/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\RouteFileRegistrar->{closure}()
#3 /var/www/myapp/vendor/laravel/framework/src/Illuminate/Routing/Route.php(179): Illuminate\\Routing\\Route->runCallable()
#4 /var/www/myapp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Routing\\Route->run()
#5 /var/www/myapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#6 /var/www/myapp/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#7 /var/www/myapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#8 /var/www/myapp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#9 /var/www/myapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
...................

**Comment by simonwestyn** [comment]
@Thedonsolo your `A2` log looks pretty empty :/ 

Could you maybe provide dumps of the `loadAndVerifyWithKeySet`-method params?
Also, what are the contents of the following: `Log::info('A1 '.$jws->countSignatures());` they seem to be missing.
It seems that there are no signatures.

It looks like the catch is never entered cause there is no error, but code never reaches the `return $jws;` so it throws that error at the end of the function.

**Comment by Thedonsolo** [comment]
@simonwestyn 
I changed the logging a bit to give you a full picture.

public function loadAndVerifyWithKeySet(string $token, JWKSet $keyset, ?int &$signature, ?string $payload = null): JWS
    {
        Log::info('TOKEN:'.$token);
        Log::info('KEYSET: ',(array)$keyset);
        Log::info('SIGNATURE:'.$signature);
        Log::info('PAYLOAD:'.$payload);
        try {
            Log::info('A1 '.$token);
            $jws = $this->serializerManager->unserialize($token);
            Log::info('A2 ',(array)$jws);

            $nbSignatures = $jws->countSignatures();
            Log::info('A3 '.$jws->countSignatures());
            for ($i = 0; $i < $nbSignatures; ++$i) {
                Log::info('A4 ',(array)$jws);
                if ($this->processSignature($jws, $keyset, $i, $payload)) {
                    $signature = $i;
                    Log::info('WILL RETURN');
                    return $jws;
                }
            }
        } catch (Throwable $e) {
            Log::info('ERROR:',(array)$e);
            // Nothing to do. Exception thrown just after
        }

        throw new Exception('Unable to load and verify the token.');
    }


**LOGGING**:

PAYLOAD: {"paymentId":"1a5987212ffdfa9304420283","transferAmount":6600,"tippingAmount":0,"amount":6600,"totalAmount":6600,"reference":"ECA7-AB72","createdAt":"2021-02-23T13:56:01.507Z","expireAt":"2021-02-23T13:59:01.507Z","succeededAt":"2021-02-23T13:56:11.646Z","status":"SUCCEEDED","debtor":{"name":"Test","iban":"*************24680"},"currency":"EUR"}  

TOKEN:eyJ0eX............................eOKg  

KEYSET:  {"\u0000Jose\\Component\\Core\\JWKSet\u0000keys":{"rs.signature.ext.2021":{"Jose\\Component\\Core\\JWK":{"kty":"RSA","use":"sig","x5t#S256":"ZHxLzy5hQqQaGJPmLl_MpDQyDrX7Y1EwZdiHAum5Xkg","e":"AQAB","kid":"rs.signature.ext.2021","alg":"RS256","x5c":["MIIF7jCCBNagAwIBAgIRAJHNVU4ve1Ki1Ewoaw3ftGQwDQYJKoZIhvcNAQELBQAwgY8xCzAJBgNV
.........................

A1: eyJ0eX............................eOKg 

A2  {"\u0000Jose\\Component\\Signature\\JWS\u0000isPayloadDetached":true,"\u0000Jose\\Component\\Signature\\JWS\u0000encodedPayload":null,"\u0000Jose\\Component\\Signature\\JWS\u0000signatures":[{"Jose\\Component\\Signature\\Signature":[]}],"\u0000Jose\\Component\\Signature\\JWS\u0000payload":null} 

A3 1  

A4  {"\u0000Jose\\Component\\Signature\\JWS\u0000isPayloadDetached":true,"\u0000Jose\\Component\\Signature\\JWS\u0000encodedPayload":null,"\u0000Jose\\Component\\Signature\\JWS\u0000signatures":[{"Jose\\Component\\Signature\\Signature":[]}],"\u0000Jose\\Component\\Signature\\JWS\u0000payload":null}

**Comment by simonwestyn** [comment]
Hi @Thedonsolo,

thanks for the info.
The issue seems to come from the `processSignature` function.

Could you provide the error that gets thrown there please?

E.g.:

```php
private function processSignature(JWS $jws, JWKSet $keyset, int $signature, ?string $payload): bool
    {
        try {
            if (null !== $this->headerCheckerManager) {
                $this->headerCheckerManager->check($jws, $signature);
            }

            return $this->jwsVerifier->verifyWithKeySet($jws, $keyset, $signature, $payload);
        } catch (Throwable $e) {
            Log::info('ERROR:', $e->getMessage()); //<<<<<<<<<<< to figure out what is going wrong
            return false;
        }
    }
```

**Comment by Thedonsolo** [comment]
Hi @simonwestyn 
Thanks for helping me, the error is **https://payconiq.com/iat\" has an invalid date format**

**Comment by simonwestyn** [comment]
Hi @Thedonsolo,

Could you provide me the contents of `$value` in `checkHeader` (`vendor/optiosteam/payconiq-client-php/src/HeaderChecker/PayconiqIssuedAtChecker.php`)

E.g.:

```php
public function checkHeader($value): void
    {
        Log::info('value:', $value); //<<<<<<<<<<< to figure out what is going wrong
        try {
            $iat = new Carbon($value);

            if ($iat->gt(Carbon::now('UTC'))) {
                throw new InvalidHeaderException(
                    'The JWT is issued in the future.',
                    self::HEADER_NAME,
                    $value
                );
            }
        } catch (\Exception $e) {
            throw new InvalidHeaderException(
                sprintf('"%s" has an invalid date format', self::HEADER_NAME),
                self::HEADER_NAME,
                $value
            );
        }
    }
```

Thanks!

**Comment by Thedonsolo** [comment]
@simonwestyn , 

Here you go : 2021-02-23T15:47:59.271019Z

**Comment by simonwestyn** [comment]
@Thedonsolo ok, that looks good. Could you also log the `$e->getMessage()` in that catch please? Thx

**Comment by Thedonsolo** [comment]
@simonwestyn  
The JWT is issued in the future.

**Comment by simonwestyn** [comment]
Seems to be a timezone issue. What timezone is set? (`echo date_default_timezone_get()`)
What is the output if you do this in your codebase: `echo Carbon::now('UTC')->format('Y-m-d H:i:s')`?

**Comment by Thedonsolo** [comment]
@simonwestyn  hmm, doesn't seem right:

TZ: Europe/Brussels 
 Carbon: 2021-02-23 16:01:59

**Comment by simonwestyn** [comment]
@Thedonsolo thanks for the info! I'll investigate further and I'll try to make a fix. I'll keep you posted here :)

**Comment by Thedonsolo** [comment]
@simonwestyn  thanks!

**Comment by simonwestyn** [comment]
@Thedonsolo I just tried this on my own computer and it seems to be working correctly for me 😕 

```php
dump(date_default_timezone_get());
dump(Carbon::now('UTC')->format('Y-m-d H:i:s'));

$iat = new Carbon('2021-02-23T15:47:59.271019Z');

if ($iat->gt(Carbon::now('UTC'))) {
    dump('bad');
} else {
    dump('good');
}
```

OUTPUT:
```
"Europe/Brussels"
"2021-02-23 16:13:17"
"good"
```

This is a long shot, but any chance that the time of your localhost is off by a few minutes?

Could you try this:
```php
if ($iat->gt(Carbon::now('UTC'))) {

                Log::info('diff in minutes:',$iat->diffInMinutes(Carbon::now('UTC'))); //<<<<<<<<<<< to figure out what is going wrong

                throw new InvalidHeaderException(
                    'The JWT is issued in the future.',
                    self::HEADER_NAME,
                    $value
                );
            }
```

**Comment by Thedonsolo** [comment]
@simonwestyn that was it!  My server was 3 mins late!

Thanks a lot for your support/time!

**Comment by simonwestyn** [comment]
@Thedonsolo awesome! 🎉  

You're welcome! Glad it worked out 😄
