### ISSUE TITLE
Error when calling requestPayment

### ISSUE THREAD

**Issue by Thedonsolo** [optiosteam/payconiq-client-php#4]
When i'm calling requestPayment to retrieve a qry code url, an error is thrown and no response is returned.
It happens sometimes on our test server, not on our local server.

Code:

`        $client = new PayconiqApiClient($this->apikey, null, false);
        $requestPayment = new RequestPayment(
            toEuroCents($order->totalamount)
        );
        $requestPayment->setCallbackUrl($this->callbackurl);
        $requestPayment->setReference($order->ordernumber);
        $requestPayment->setPosId("POS00001");

        $payment = $client->requestPayment($requestPayment);
        Log::info('PAYYYYYYYYYYYYYYYYY: ',(array)$payment);
        if(!is_null($payment) && $payment->getStatus() == 'PENDING'){
            $return['paymentid'] = $payment->getPaymentId();
            $return['status'] = $payment->getStatus();
            $return['qrcode'] = $payment->getQrLink();
            $return['deeplink'] = $payment->getDeepLink();

            return $return;
        }
        else{
            return false;
        }`

Error:
Call to undefined method GuzzleHttp\Exception\ConnectException::getResponse() {"userId":"5f22b6ba1d4a35.44007502","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined method GuzzleHttp\\Exception\\ConnectException::getResponse() at /var/www/myapp/vendor/optiosteam/payconiq-client-php/src/PayconiqApiClient.php:225)
[stacktrace]
#0 /var/www/myapp/vendor/optiosteam/payconiq-client-php/src/PayconiqApiClient.php(90): Optios\\Payconiq\\PayconiqApiClient->convertToPayconiqApiException(Object(GuzzleHttp\\Exception\\ConnectException))
#1 /var/www/myapp/app/Http/Controllers/PayconiqController.php(77): Optios\\Payconiq\\PayconiqApiClient->requestPayment(Object(Optios\\Payconiq\\Request\\RequestPayment))
#2 /var/www/myapp/routes/web.php(406): App\\Http\\Controllers\\PayconiqController->getPaymentQR(Object(App\\Order))
#3 /var/www/myapp/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\RouteFileRegistrar->{closure}('5f88646e57c527....')
#4 /var/www/myapp/vendor/laravel/framework/src/Illuminate/Routing/Route.php(179): Illuminate\\Routing\\Route->runCallable()
#5 /var/www/myapp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Routing\\Route->run()
#6 /var/www/myapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#7 /var/www/myapp/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#8 /var/www/myapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))

**Comment by simonwestyn** [comment]
Hi @Thedonsolo, 

In the `requestPayment`-method, could you comment out `| GuzzleException`, like this:

```php
} catch (ClientException /*| GuzzleException*/ $e) {
```

I think I'm catching an Exception that probably shouldn't be caught there.

The actual error you are getting on your test server is probably a `GuzzleException`, that will give you more information.

Please report back so I create a Pull Request and create a new version :)

**Comment by simonwestyn** [comment]
@Thedonsolo I created a new release (`1.0.3`) that should fix the wrongful catching of the `GuzzleException`.

You can update the package with `composer`

**Comment by Thedonsolo** [comment]
Hi @simonwestyn , solved!
Thanks!
